name: Continuous Integration (CI)

on:
  push:
  pull_request:

jobs:
  test:
    name: Test + Quality
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build + Test + Lint
        run: ./gradlew clean check jacocoTestReport

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.GHANI_SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=group-1-kki-adpro
            -Dsonar.projectKey=Group-1-KKI-Adpro_Individual-Preparation
            -Dsonar.java.binaries=build/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml